"""Verified KCD2 XML/ZIP packaging; never treats Blender GLB as game data."""
from __future__ import annotations

import hashlib
import json
import math
import re
import xml.etree.ElementTree as ET
import zipfile
from datetime import date
from pathlib import Path, PurePosixPath

from runtime_tools import REGISTRY_VERSION, RUNTIME_VERSION


def mod_id(value: str) -> str:
    # Warhorse KM-A-57 explicitly restricts IDs to lowercase letters/underscore.
    if not re.fullmatch(r"[a-z][a-z_]{0,63}", value):
        raise ValueError("KCD2 mod IDs must contain only lowercase letters and underscores.")
    return value


def virtual_path(value: str) -> str:
    p = PurePosixPath(value.replace("\\", "/"))
    if p.is_absolute() or not p.parts or any(x in ("..", ".") for x in p.parts) or ":" in value:
        raise ValueError(f"Unsafe game data path: {value!r}")
    return str(p)


def write_manifest(target: Path, project) -> None:
    root = ET.Element("kcd_mod")
    info = ET.SubElement(root, "info")
    for key, value in (("name", project.name), ("modid", mod_id(project.id)),
                       ("description", project.description), ("author", project.author),
                       ("version", project.version), ("created_on", date.today().isoformat()),
                       ("modifies_level", "false")):
        ET.SubElement(info, key).text = str(value)
    ET.indent(root)
    target.write_bytes(ET.tostring(root, encoding="utf-8", xml_declaration=True))


def lua_literal(value) -> str:
    """Serialize data only. Lua 5.1 escapes use fixed-width decimal bytes."""
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (float, int)):
        if not math.isfinite(value):
            raise ValueError("Nonfinite registry number")
        return repr(value)
    if isinstance(value, str):
        return '"' + "".join(chr(b) if 32 <= b < 127 and b not in (34, 92)
                             else f"\\{b:03d}" for b in value.encode("utf-8")) + '"'
    if isinstance(value, list):
        return "{" + ",".join(map(lua_literal, value)) + "}"
    if isinstance(value, dict):
        return "{" + ",".join(f"[{lua_literal(k)}]={lua_literal(v)}" for k, v in sorted(value.items())) + "}"
    raise TypeError(type(value).__name__)


GAITS_SCRIPT = "Scripts/ModMaster/gaits.lua"


def gaits_lua(gaits: dict[str, dict[str, str]]) -> bytes:
    """How every animal body walks, for the in-game menu that moves spawned creatures with their own gaits."""
    return ("-- Generated by ModMaster. Data only; do not edit installed copy.\n"
            + "ModMasterGaits = " + lua_literal(gaits) + "\n").encode("utf-8")


def registry_lua(registry: dict) -> bytes:
    if registry.get("format_version") != REGISTRY_VERSION:
        raise ValueError("Incompatible registry version")
    return ("-- Generated by ModMaster. Data only; do not edit installed copy.\n"
            + "ModMasterRegistry = " + lua_literal(registry) + "\n").encode("utf-8")


def pack_data(source: Path, output: Path, extra: dict[str, bytes] | None = None) -> None:
    if source.is_symlink() or source.is_junction():
        raise ValueError("Linked game data root")
    output.parent.mkdir(parents=True, exist_ok=True)
    entries = {}
    if source.exists():
        for p in source.rglob("*"):
            if p.is_symlink() or p.is_junction():
                raise ValueError(f"Linked game data is not accepted: {p}")
            if p.is_file():
                key = virtual_path(p.relative_to(source).as_posix())
                if p.suffix.lower() in (".blend", ".glb", ".gltf", ".fbx", ".py"):
                    raise ValueError(f"Uncompiled/source file in game payload: {key}")
                entries[key] = p.read_bytes()
    entries.update(extra or {})
    seen = set()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_STORED) as z:
        for key, data in sorted(entries.items()):
            key = virtual_path(key)
            if key.casefold() in seen:
                raise ValueError(f"Duplicate game data path: {key}")
            seen.add(key.casefold())
            item = zipfile.ZipInfo(key, (2025, 1, 1, 0, 0, 0))
            z.writestr(item, data)


def hashes(root: Path) -> dict[str, str]:
    return {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(root.rglob("*")) if p.is_file() and p.name != ".modmaster-install.json"}


def read_spawn_descriptors(project) -> list[dict]:
    """Explicit descriptor is ModMaster's schema, not an invented KCD2 entity schema.

    Existing BasicEntity supports arbitrary compiled static CGF via object_Model.
    Inventory items require a real GUID in a packaged database XML and compiled dependencies.
    """
    path = Path(project.project_dir) / "runtime_assets.json"
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("format_version") != REGISTRY_VERSION or not isinstance(data.get("assets"), list):
        raise ValueError("Invalid runtime_assets.json")
    result, ids = [], set()
    for raw in data["assets"]:
        aid = str(raw["id"])
        if not aid or len(aid) > 128 or aid in ids:
            raise ValueError("Invalid/duplicate runtime asset ID")
        ids.add(aid)
        spawn_type = raw.get("spawn_type", "static_prop")
        if spawn_type == "inventory_item":
            import uuid
            try:
                guid = str(uuid.UUID(str(raw["item_guid"])))
            except (ValueError, KeyError, AttributeError) as exc:
                raise ValueError("Inventory item requires its real item database GUID") from exc
            category = str(raw.get("category", "weapons"))
            if category not in ("weapons", "armor"):
                raise ValueError("Inventory adapter supports weapons and armor")
            if raw.get("source") == "verified_game_reference":
                # A single transparent test fixture evidenced in the retail player script.
                if (project.id != "modmaster_runtime_test" or not raw.get("evidence")
                        or guid != "196be21b-6d21-4dd6-84e4-c95ecd2092a7"):
                    raise ValueError("Game inventory references are limited to the inspected mace test fixture")
                result.append({"id": aid, "name": str(raw.get("name", aid)), "category": category,
                               "spawn_type": "inventory_item", "item_guid": guid,
                               "status": "retail_script_reference_unverified", "source": "verified_game_reference"})
                continue
            tables = raw.get("database_files")
            if not isinstance(tables, list) or not tables:
                raise ValueError("Declare the packaged item database XML files")
            found = False
            game_root = Path(project.project_dir) / "game"
            for name in tables:
                filename = virtual_path(name)
                if not filename.lower().endswith(".xml"):
                    raise ValueError("Item database declaration must reference XML")
                file = game_root / filename
                if not file.is_file():
                    raise ValueError(f"Missing item database: {filename}")
                tree = ET.parse(file)
                found |= any(str(v).lower() == guid for node in tree.iter() for v in node.attrib.values())
            if not found:
                raise ValueError("Item GUID is absent from the declared database XML")
            dependencies = raw.get("dependencies", [])
            if not isinstance(dependencies, list) or not dependencies:
                raise ValueError("Declare compiled item model/material/texture dependencies")
            for dependency in dependencies:
                file = game_root / virtual_path(dependency)
                if not file.is_file() or file.suffix.lower() in (".blend", ".glb", ".gltf", ".fbx"):
                    raise ValueError(f"Missing/uncompiled item dependency: {dependency}")
            result.append({"id": aid, "name": str(raw.get("name", aid)), "category": category,
                           "spawn_type": "inventory_item", "item_guid": guid,
                           "status": "packaged_unverified", "source": "compiled_custom"})
            continue
        if spawn_type != "static_prop":
            raise ValueError("Only static_prop has a verified entity adapter in this version")
        model = virtual_path(raw["model_path"])
        if not model.lower().endswith(".cgf"):
            raise ValueError("Static prop requires compiled .cgf")
        reference = raw.get("source") == "verified_game_reference"
        if reference:
            if not raw.get("evidence"):
                raise ValueError("Game model reference requires inspection evidence")
            if project.id != "modmaster_runtime_test":
                raise ValueError("Vanilla model references are limited to the inspected runtime test project")
        else:
            root = Path(project.project_dir) / "game"
            file = root / model
            if not file.is_file() or not file.read_bytes().startswith(b"CrCh"):
                raise ValueError(f"Missing/invalid compiled CGF: {model}")
            # Require a declared split mesh and dependencies rather than guessing completeness.
            dependencies = raw.get("dependencies")
            if not isinstance(dependencies, list) or not dependencies:
                raise ValueError(f"Declare compiled mesh/material/texture dependencies for {aid}")
            for dependency in dependencies:
                dep = root / virtual_path(dependency)
                if not dep.is_file():
                    raise ValueError(f"Missing runtime dependency: {dependency}")
        result.append({"id": aid, "name": str(raw.get("name", aid)),
                       "category": str(raw.get("category", "props")),
                       "spawn_type": spawn_type, "spawn_id": f"{project.id}:{aid}",
                       "model_path": model, "status": "packaged_unverified",
                       "lods": raw.get("lods", []), "physics": False,
                       "source": raw.get("source", "compiled_custom")})
    return result
